# Generated by Django 4.2.6 on 2023-11-15 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preview_image', models.ImageField(upload_to='')),
                ('preview_text', models.CharField(max_length=50)),
                ('story_header', models.CharField(max_length=250)),
                ('story_description', models.CharField(default='', max_length=200)),
                ('have_story_button', models.BooleanField(default=False)),
                ('link_story_button', models.URLField(default='')),
            ],
            options={
                'verbose_name': 'story',
                'verbose_name_plural': 'stories',
            },
        ),
        migrations.CreateModel(
            name='StoryImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_1', models.ImageField(upload_to='')),
                ('image_2', models.ImageField(upload_to='')),
                ('image_3', models.ImageField(upload_to='')),
                ('image_4', models.ImageField(upload_to='')),
                ('image_5', models.ImageField(upload_to='')),
                ('image_6', models.ImageField(upload_to='')),
                ('image_7', models.ImageField(upload_to='')),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stories.story')),
            ],
        ),
    ]
